"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var chai_1 = require("chai");
var string_1 = require("../../lib/utils/string");
/**
 * Checks auto generated functions on targets prototype
 */
function expectAutoGeneratedFunctions(target, keys) {
    var prefixes = {
        toMany: {
            singular: ['create', 'remove', 'has'],
            plural: ['add', 'count', 'get', 'set', 'remove', 'has']
        },
        toOne: {
            singular: ['create', 'get', 'set'],
            plural: []
        }
    };
    var finalPrefixes = prefixes[keys.plural ? 'toMany' : 'toOne'];
    Object
        .keys(keys)
        .forEach(function (key) {
        finalPrefixes[key].forEach(function (prefix) {
            chai_1.expect(target.prototype)
                .to.have.property(prefix + string_1.capitalize(keys[key]))
                .that.is.a('function');
        });
    });
}
exports.expectAutoGeneratedFunctions = expectAutoGeneratedFunctions;
//# sourceMappingURL=association.js.map